package(default_visibility=['//visibility:public'])

cc_library(
    name='a',
    hdrs=[
        'a.h',
#        'b.h',
    ],
    strip_include_prefix='',
)

cc_library(
    name='b',
    hdrs=['b.h'],
    strip_include_prefix='',
)
